spring:
  datasource:
    url:  jdbc:mysql://localhost/test
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
# JPA
jpa:
  hibernate:
  ddl-auto: update
  show-sql: true
# Thymeleaf
thymeleaf:
  cache: false